version: '3.8'

services:
  clovett_react:
    build:
      context: .
    container_name: clovett_react
    ports:
      - "3000:3000"
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - clovett_react